Preserve Music and genre data
yosefHesham/Catalog-My-Things pull request #35
Opened 2023-02-16 21:05 UTC by momotsow

- Display all created music options
- Display all created genres
- Add music album
- Create a schema.sql file with tables that will be analogical to the structure of the classes
- Preserve Music data in Json file
- Preserve Genre data in Json file

2023-02-16 22:21 UTC, yosefHesham requested changes
Hey @momotsow  !
You have done a great job !, however there is some changes.

Please review the below comments

2023-02-16 22:22 UTC, yosefHesham commented on database/schema.sql
> +<<<<<<< HEAD
Remove this <<<HEAD please

2023-02-16 22:22 UTC, yosefHesham commented on database/schema.sql
> +=======
Also this

2023-02-16 22:22 UTC, yosefHesham commented on database/schema.sql
> +>>>>>>> eb22764f69c9f5096ca875f6940f701b86c68e22
the last thing =D

2023-02-17 06:47 UTC, vanelnw approved these changes
# STATUS: MILESTONE APPROVED 👍 

Hi @momotsow   , 
### Great job !!!

Your task is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  No linter errors
:heavy_check_mark:  Very descriptive and detailed PR

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 06:55 UTC, merged